import { useEffect, useState, type ReactNode } from 'react';
import { KeyRound, Pencil, Plus, Settings2 } from 'lucide-react';
import type { MemoryConfig, ProviderConfig } from '../../shared/configuration';
import { usePreferences } from '../preferences';
import { Button } from '../components/ui/button';
import { Input } from '../components/ui/input';
import { Select } from '../components/ui/select';
import { Modal } from '../components/ui/modal';
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="block space-y-2 text-sm"><span className="text-muted-foreground">{label}</span>{children}</label>; }
export function Providers({ connected }: { connected: boolean }) {
  const ru = usePreferences().language === 'ru'; const [snapshot, setSnapshot] = useState<{ hash: string; providers: ProviderConfig[] } | null>(null); const [error, setError] = useState(''); const [editor, setEditor] = useState<ProviderConfig | null>(null);
  const load = async () => { const result = await window.pincer.configuration.providers(); if (result.ok) setSnapshot(result.value); else setError(result.error.message); };
  useEffect(() => { if (connected) void load(); }, [connected]);
  return <section className="mb-10"><div className="mb-4 flex items-center justify-between gap-2"><h2 className="text-lg font-semibold">{ru ? 'Провайдеры' : 'Providers'}</h2><Button variant="outline" className="h-9 rounded-full" disabled={!connected || !snapshot} onClick={() => setEditor({ id: '', baseUrl: '', api: 'openai-completions', models: [], hasKey: false })}><Plus size={14} className="mr-2" />{ru ? 'Добавить провайдера' : 'Add provider'}</Button></div>
    {error && <p role="alert" className="mb-3 text-sm text-destructive">{error}</p>}<div className="space-y-2">{snapshot?.providers.map((provider) => <div key={provider.id} className="flex items-center gap-4 rounded-2xl bg-black/[0.035] p-4 dark:bg-white/[0.045]"><div className="rounded-xl bg-primary/10 p-2.5 text-primary"><KeyRound size={20} /></div><div className="min-w-0 flex-1"><h3 className="font-medium">{provider.id}</h3><p className="truncate text-xs text-muted-foreground">{provider.baseUrl} · {provider.models.length} {ru ? 'моделей' : 'models'}</p></div><Button size="icon" variant="ghost" aria-label={`${ru ? 'Настроить провайдера' : 'Configure provider'}: ${provider.id}`} disabled={!connected} onClick={() => setEditor(provider)}><Settings2 size={16} /></Button></div>)}</div>
    {snapshot && !snapshot.providers.length && <p className="text-sm text-muted-foreground">{ru ? 'Дополнительные провайдеры не настроены. Встроенные модели показаны ниже.' : 'No custom providers are configured. Built-in models are listed below.'}</p>}
    {editor && snapshot && <ProviderEditor value={editor} hash={snapshot.hash} close={() => setEditor(null)} saved={() => { setEditor(null); void load(); void window.pincer.chat.refresh(); }} />}
  </section>;
}
function ProviderEditor({ value, hash, close, saved }: { value: ProviderConfig; hash: string; close(): void; saved(): void }) {
  const ru = usePreferences().language === 'ru'; const [id, setId] = useState(value.id); const [url, setUrl] = useState(value.baseUrl); const [api, setApi] = useState(value.api || 'openai-completions'); const [key, setKey] = useState(''); const [models, setModels] = useState(value.models.join('\n')); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  return <Modal open title={ru ? 'Провайдер моделей' : 'Model provider'} close={() => { if (!busy) close(); }}><form className="max-h-[65vh] space-y-4 overflow-auto" onSubmit={(event) => { event.preventDefault(); setBusy(true); setError(''); void window.pincer.configuration.saveProvider(hash, { id, baseUrl: url, api, models: models.split('\n').map((model) => model.trim()).filter(Boolean), ...(key ? { apiKey: key } : {}) }).then((result) => { if (result.ok) { setKey(''); saved(); } else setError(result.error.message); }).finally(() => setBusy(false)); }}>
    <Field label={ru ? 'Идентификатор провайдера' : 'Provider ID'}><Input value={id} disabled={Boolean(value.id)} required pattern="[a-z][a-z0-9_-]*" onChange={(event) => setId(event.target.value)} /></Field>
    <Field label={ru ? 'Базовый адрес' : 'Base URL'}><Input required type="url" value={url} onChange={(event) => setUrl(event.target.value)} placeholder="https://api.example.com/v1" /></Field>
    <Field label="API"><Select className="w-full" value={api} onChange={(event) => setApi(event.target.value)}>{['openai-completions', 'openai-responses', 'anthropic-messages', 'ollama'].map((item) => <option key={item}>{item}</option>)}</Select></Field>
    <Field label={ru ? 'API-ключ' : 'API key'}><Input type="password" autoComplete="off" value={key} onChange={(event) => setKey(event.target.value)} placeholder={value.hasKey ? ru ? 'Ключ настроен · пустое поле сохранит его' : 'Configured · leave blank to keep' : ru ? 'Необязательно' : 'Optional'} /></Field>
    <Field label={ru ? 'Модели — по одной на строку' : 'Model IDs — one per line'}><textarea required className="min-h-24 w-full rounded-xl border border-border bg-background p-3 font-mono text-xs" value={models} onChange={(event) => setModels(event.target.value)} /></Field>
    <p className="text-xs leading-5 text-muted-foreground">{ru ? 'Настройки сохраняются на Gateway. Он может перезапуститься для их применения. Существующий ключ не возвращается в интерфейс.' : 'Settings are saved on the Gateway, which may restart to apply them. Existing keys are never returned to this UI.'}</p>
    {error && <p role="alert" className="text-sm text-destructive">{error === 'CONFIG_CONFLICT' ? ru ? 'Настройки изменились на сервере. Закройте форму и обновите страницу.' : 'Settings changed on the server. Close the form and refresh.' : error}</p>}<Button disabled={busy || !id || !url || !models.trim()}>{ru ? 'Сохранить на Gateway' : 'Save to Gateway'}</Button>
  </form></Modal>;
}
export function MemoryConfiguration({ connected, saved }: { connected: boolean; saved(): void }) {
  const ru = usePreferences().language === 'ru'; const [open, setOpen] = useState(false);
  return <><Button variant="outline" disabled={!connected} onClick={() => setOpen(true)}><Pencil size={14} className="mr-2" />{ru ? 'Настроить векторный поиск' : 'Configure vector search'}</Button>{open && <MemoryEditor close={() => setOpen(false)} saved={() => { setOpen(false); saved(); }} />}</>;
}
function MemoryEditor({ close, saved }: { close(): void; saved(): void }) {
  const ru = usePreferences().language === 'ru'; const [snapshot, setSnapshot] = useState<MemoryConfig | null>(null); const [provider, setProvider] = useState(''); const [model, setModel] = useState(''); const [url, setUrl] = useState(''); const [key, setKey] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  useEffect(() => { let active = true; void window.pincer.configuration.memory().then((result) => { if (!active) return; if (result.ok) { setSnapshot(result.value); setProvider(result.value.provider); setModel(result.value.model); setUrl(result.value.baseUrl); } else setError(result.error.message); }); return () => { active = false; }; }, []);
  return <Modal open title={ru ? 'Семантическая память' : 'Semantic memory'} close={() => { if (!busy) close(); }}><form className="space-y-4" onSubmit={(event) => { event.preventDefault(); if (!snapshot) return; setBusy(true); setError(''); void window.pincer.configuration.saveMemory(snapshot.hash, { provider, model, ...(url ? { baseUrl: url } : {}), ...(key ? { apiKey: key } : {}) }).then((result) => { if (result.ok) { setKey(''); saved(); } else setError(result.error.message); }).finally(() => setBusy(false)); }}>
    <p className="text-sm text-muted-foreground">{ru ? 'Общие настройки поиска памяти на Gateway. Применяются к агентам без собственных переопределений.' : 'Gateway-wide memory search defaults. Agents with their own overrides retain them.'}</p>
    <Field label={ru ? 'Поставщик векторных представлений' : 'Embedding provider'}><Input list="embedding-providers" required value={provider} onChange={(event) => setProvider(event.target.value)} /><datalist id="embedding-providers">{['openai', 'openai-compatible', 'gemini', 'voyage', 'mistral', 'ollama', 'lmstudio', 'local', 'none'].map((name) => <option key={name} value={name} />)}</datalist></Field>
    <Field label={ru ? 'Модель векторных представлений' : 'Embedding model'}><Input value={model} onChange={(event) => setModel(event.target.value)} placeholder="text-embedding-3-small" /></Field>
    <Field label={ru ? 'Базовый адрес' : 'Base URL'}><Input type="url" value={url} onChange={(event) => setUrl(event.target.value)} /></Field><Field label={ru ? 'API-ключ' : 'API key'}><Input type="password" autoComplete="off" value={key} onChange={(event) => setKey(event.target.value)} placeholder={snapshot?.hasKey ? ru ? 'Настроен · оставить без изменения' : 'Configured · leave unchanged' : ''} /></Field>
    <p className="text-xs leading-5 text-muted-foreground">{ru ? 'OAuth для чата не заменяет ключ векторного поиска. Смена модели может потребовать переиндексации на сервере. После сохранения проверьте поиск: Pincer не считает индекс готовым без проверки.' : 'Chat OAuth does not replace embedding credentials. Changing the model may require server-side reindexing. Check search after saving; Pincer does not assume the index is ready.'}</p>
    {error && <p role="alert" className="text-sm text-destructive">{error}</p>}<Button disabled={!snapshot || !provider || busy}>{ru ? 'Сохранить на Gateway' : 'Save to Gateway'}</Button>
  </form></Modal>;
}
