import { useEffect, useState } from 'react';
import { Check, RefreshCw, Server, Trash2, UserRound, X } from 'lucide-react';
import { toast } from 'sonner';
import type { DevicePair, DevicesSnapshot, GatewayLogTail, UserProfile } from '../../shared/gateway-admin';
import { Button } from '../components/ui/button';
import { Input } from '../components/ui/input';
import { Modal } from '../components/ui/modal';
import { usePreferences } from '../preferences';

export function ProfileSettings({ connected }: { connected: boolean }) {
  const ru = usePreferences().language === 'ru'; const [value, setValue] = useState<UserProfile | null>(null); const [name, setName] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const load = () => { if (!connected) return; setError(''); void window.pincer.gatewayAdmin.profile().then(result => { if (result.ok) { setValue(result.value); setName(result.value.displayName || ''); } else setError(result.error.message); }); };
  useEffect(load, [connected]);
  return <section className="space-y-5"><div><h2 className="openx-section-title">{ru ? 'Профиль' : 'Profile'}</h2><p className="text-sm text-muted-foreground">{ru ? 'Профиль пользователя на подключённом Gateway.' : 'Your profile on the connected Gateway.'}</p></div>{error && <p role="alert" className="text-sm text-destructive">{error}</p>}{value && <form className="space-y-4 rounded-2xl border border-border bg-surface-modal p-5" onSubmit={e => { e.preventDefault(); setBusy(true); setError(''); void window.pincer.gatewayAdmin.setDisplayName(value.id, name).then(result => { if (result.ok) { setValue(result.value); setName(result.value.displayName || ''); toast.success(ru ? 'Профиль обновлён' : 'Profile updated'); } else setError(result.error.message); }).finally(() => setBusy(false)); }}><div className="flex items-center gap-3"><span className="rounded-full bg-primary/10 p-3 text-primary"><UserRound size={20} /></span><div><p className="font-medium">{value.displayName || value.id}</p><p className="text-xs text-muted-foreground">{value.role || '—'}</p></div></div><label className="block text-xs text-muted-foreground">{ru ? 'Отображаемое имя' : 'Display name'}<Input className="mt-2" value={name} maxLength={120} onChange={e => setName(e.target.value)} /></label>{value.emails.length > 0 && <div><p className="text-xs text-muted-foreground">Email</p>{value.emails.map(email => <p key={email} className="mt-1 text-sm">{email}</p>)}</div>}{value.github && <div><p className="text-xs text-muted-foreground">GitHub</p><p className="mt-1 text-sm">@{value.github.login}</p></div>}<Button disabled={busy || (value.displayName || '') === name}>{ru ? 'Сохранить на Gateway' : 'Save on Gateway'}</Button></form>}</section>;
}

function DeviceCard({ item, pending, action }: { item: DevicePair; pending?: boolean; action(action: 'approve' | 'reject' | 'remove' | 'rename', item: DevicePair): void }) {
  const ru = usePreferences().language === 'ru'; const [name, setName] = useState(item.displayName);
  return <article className="rounded-2xl border border-border bg-surface-modal p-4"><div className="flex items-start gap-3"><span className="rounded-xl bg-primary/10 p-2.5 text-primary"><Server size={18} /></span><div className="min-w-0 flex-1"><h3 className="truncate font-medium">{item.displayName}</h3><p className="mt-1 break-all text-xs text-muted-foreground">{[item.platform, item.clientId, item.deviceId].filter(Boolean).join(' · ')}</p><p className="mt-2 text-xs text-muted-foreground">{item.roles.join(', ') || '—'} · {item.scopes.join(', ') || '—'}</p></div>{item.connected !== undefined && <span className={item.connected ? 'text-xs text-green-600 dark:text-green-400' : 'text-xs text-muted-foreground'}>{item.connected ? ru ? 'Подключено' : 'Connected' : ru ? 'Не в сети' : 'Offline'}</span>}</div>{pending ? <div className="mt-4 flex gap-2"><Button size="sm" onClick={() => action('approve', item)}><Check size={14} className="mr-1" />{ru ? 'Одобрить' : 'Approve'}</Button><Button size="sm" variant="outline" onClick={() => action('reject', item)}><X size={14} className="mr-1" />{ru ? 'Отклонить' : 'Reject'}</Button></div> : <div className="mt-4 flex gap-2"><Input aria-label={`${ru ? 'Имя устройства' : 'Device name'} ${item.displayName}`} value={name} maxLength={120} onChange={e => setName(e.target.value)} /><Button size="sm" variant="outline" disabled={!name.trim() || name === item.displayName} onClick={() => action('rename', { ...item, displayName: name })}>{ru ? 'Переименовать' : 'Rename'}</Button><Button size="icon" variant="ghost" aria-label={`${ru ? 'Удалить устройство' : 'Remove device'} ${item.displayName}`} onClick={() => action('remove', item)}><Trash2 size={15} /></Button></div>}</article>;
}
export function DevicesSettings({ connected }: { connected: boolean }) {
  const ru = usePreferences().language === 'ru'; const [value, setValue] = useState<DevicesSnapshot | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [confirm, setConfirm] = useState<{ action: 'reject' | 'remove'; item: DevicePair } | null>(null);
  const load = () => { if (!connected) return; setError(''); void window.pincer.gatewayAdmin.devices().then(result => result.ok ? setValue(result.value) : setError(result.error.message)); };
  useEffect(load, [connected]);
  const perform = (action: 'approve' | 'reject' | 'remove' | 'rename', item: DevicePair) => { if ((action === 'remove' || action === 'reject') && !confirm) { setConfirm({ action, item }); return; } setBusy(true); setError(''); void window.pincer.gatewayAdmin.deviceAction(action, action === 'approve' || action === 'reject' ? item.requestId || '' : item.deviceId, action === 'rename' ? item.displayName : undefined).then(result => { if (result.ok) { setConfirm(null); load(); } else setError(result.error.message); }).finally(() => setBusy(false)); };
  return <section className="space-y-5"><div className="flex items-center justify-between"><div><h2 className="openx-section-title !mb-2">{ru ? 'Узлы и устройства' : 'Nodes and devices'}</h2><p className="text-sm text-muted-foreground">{ru ? 'Реальные запросы связывания и одобренные устройства Gateway.' : 'Live pairing requests and approved Gateway devices.'}</p></div><Button size="icon" variant="ghost" disabled={busy || !connected} onClick={load} aria-label={ru ? 'Обновить устройства' : 'Refresh devices'}><RefreshCw size={16} /></Button></div>{error && <p role="alert" className="text-sm text-destructive">{error}</p>}{value && <><div><h3 className="mb-3 text-sm font-semibold">{ru ? 'Ожидают одобрения' : 'Pending approval'} · {value.pending.length}</h3><div className="space-y-2">{value.pending.map(item => <DeviceCard key={item.requestId || item.deviceId} item={item} pending action={perform} />)}{!value.pending.length && <p className="text-sm text-muted-foreground">{ru ? 'Нет ожидающих запросов.' : 'No pending requests.'}</p>}</div></div><div><h3 className="mb-3 text-sm font-semibold">{ru ? 'Связанные устройства' : 'Paired devices'} · {value.paired.length}</h3><div className="space-y-2">{value.paired.map(item => <DeviceCard key={item.deviceId} item={item} action={perform} />)}</div></div></>}{confirm && <Modal open title={confirm.action === 'remove' ? ru ? 'Удалить устройство?' : 'Remove device?' : ru ? 'Отклонить запрос?' : 'Reject request?'} close={() => { if (!busy) setConfirm(null); }}><p className="text-sm text-muted-foreground">{confirm.item.displayName}</p><div className="mt-5 flex justify-end gap-2"><Button variant="ghost" disabled={busy} onClick={() => setConfirm(null)}>{ru ? 'Отмена' : 'Cancel'}</Button><Button disabled={busy} onClick={() => perform(confirm.action, confirm.item)}>{ru ? 'Подтвердить' : 'Confirm'}</Button></div></Modal>}</section>;
}

export function LogsSettings({ connected }: { connected: boolean }) {
  const ru = usePreferences().language === 'ru'; const [value, setValue] = useState<GatewayLogTail | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const load = (cursor = 0) => { if (!connected) return; setBusy(true); setError(''); void window.pincer.gatewayAdmin.logs(cursor).then(result => { if (result.ok) setValue(old => cursor && old ? { ...result.value, lines: [...old.lines, ...result.value.lines].slice(-1000) } : result.value); else setError(result.error.message); }).finally(() => setBusy(false)); };
  useEffect(() => load(0), [connected]);
  return <section className="space-y-5"><div className="flex items-center justify-between"><div><h2 className="openx-section-title !mb-2">{ru ? 'Журналы Gateway' : 'Gateway logs'}</h2><p className="text-sm text-muted-foreground">{ru ? 'Последние строки журнала. Учетные данные дополнительно скрываются Pincer.' : 'Recent Gateway log lines. Pincer applies additional credential redaction.'}</p></div><Button variant="outline" disabled={busy || !connected} onClick={() => load(value?.cursor || 0)}><RefreshCw size={14} className="mr-2" />{ru ? 'Обновить' : 'Refresh'}</Button></div>{error && <p role="alert" className="text-sm text-destructive">{error}</p>}<pre className="openx-copy-surface min-h-72 max-h-[58vh] overflow-auto whitespace-pre-wrap break-all rounded-2xl border border-border bg-surface-modal p-4 font-mono text-xs leading-5">{value?.lines.join('\n') || (busy ? ru ? 'Загрузка…' : 'Loading…' : ru ? 'Журнал пуст.' : 'Log is empty.')}</pre></section>;
}
