import { useEffect, useMemo, useState } from 'react';
import { ChevronDown, Plus, Search, RotateCcw, LockKeyhole, SlidersHorizontal, Code2 } from 'lucide-react';
import { toast } from 'sonner';
import { Button } from '../components/ui/button';
import { Input } from '../components/ui/input';
import { Modal } from '../components/ui/modal';
import { Select } from '../components/ui/select';
import { usePreferences } from '../preferences';
import { isProtectedSetting, resolveSchema, settingHint, type JsonSchema, type JsonValue, type SettingHint, type SettingsCatalog, type SettingsDocument } from '../../shared/settings';
import { gatewayCategories, rootLabels } from './settings-categories';

const obj = (value: unknown): Record<string, JsonValue> => value && typeof value === 'object' && !Array.isArray(value) ? value as Record<string, JsonValue> : {};
const seed = (schema: JsonSchema): JsonValue => schema.default ?? schema.const ?? (schema.type === 'object' || schema.properties ? Object.fromEntries(Object.entries(schema.properties || {}).filter(([, s]) => s.const !== undefined).map(([k, s]) => [k, s.const!])) : schema.type === 'array' ? [] : schema.type === 'boolean' ? false : ['number', 'integer'].includes(String(schema.type)) ? 0 : '');
const errorText = (code: string, ru: boolean) => ({
  CONFIG_CONFLICT: ru ? 'Настройки уже изменены на сервере. Обновите раздел и повторите правки.' : 'Server settings changed. Reload this section and reapply your changes.',
  SECRET_REFERENCE_MOVED: ru ? 'Нельзя переставить скрытый секрет на другое место. Укажите его заново или сохраните исходный порядок.' : 'A hidden secret cannot be moved to another position. Enter it again or keep the original order.',
  NEW_DESTINATION_REQUIRES_NEW_KEY: ru ? 'При смене адреса укажите новый ключ: сохранённый секрет не будет отправлен на другой сервер.' : 'Enter a new key when changing the endpoint. Saved credentials will not be moved to another server.',
  SETTINGS_SAVE_FAILED: ru ? 'Gateway не принял настройки. Проверьте типы и обязательные поля. Значения секретов не выводятся в ошибку.' : 'Gateway rejected these settings. Check types and required fields. Secret values are excluded from errors.',
}[code] || code);

function JsonField({ value, set, label, sensitive }: { value: JsonValue | undefined; set(value: JsonValue | undefined): void; label: string; sensitive?: boolean }) {
  const ru = usePreferences().language === 'ru'; const [text, setText] = useState(() => isProtectedSetting(value) ? '' : JSON.stringify(value ?? null, null, 2)); const [error, setError] = useState(false);
  useEffect(() => { setText(isProtectedSetting(value) ? '' : JSON.stringify(value ?? null, null, 2)); setError(false); }, [value]);
  return <div className="space-y-2"><textarea aria-label={label} spellCheck={false} autoComplete="off" className="min-h-28 w-full rounded-xl border border-border bg-background p-3 font-mono text-xs" placeholder={sensitive ? ru ? 'Секрет сохранён. Введите JSON для замены.' : 'Secret saved. Enter JSON to replace.' : 'JSON'} value={text} onChange={e => { setText(e.target.value); setError(false); }} /><Button size="sm" variant="outline" type="button" onClick={() => { try { set(JSON.parse(text)); setError(false); } catch { setError(true); } }}>{ru ? 'Применить JSON к черновику' : 'Apply JSON to draft'}</Button>{error && <p role="alert" className="text-xs text-destructive">{ru ? 'Некорректный JSON. Черновик не изменён.' : 'Invalid JSON. Draft unchanged.'}</p>}</div>;
}

function SchemaField({ schema, value, set, path, hints, depth = 0, query = '' }: { schema: JsonSchema; value?: JsonValue; set(value: JsonValue | undefined): void; path: string[]; hints: Record<string, SettingHint>; depth?: number; query?: string }) {
  const ru = usePreferences().language === 'ru'; const [open, setOpen] = useState(depth === 0); const [newKey, setNewKey] = useState(''); const [raw, setRaw] = useState(false); const [variant, setVariant] = useState<number | null>(null);
  const variants = schema.anyOf || schema.oneOf;
  const node = variant !== null && variants?.[variant] ? resolveSchema(variants[variant], value) : resolveSchema(schema, value); const hint = settingHint(hints, path);
  const label = hint.label || node.title || path.at(-1) || ''; const help = hint.help || node.description;
  const fieldPath = path.join('.'); const protectedValue = isProtectedSetting(value);
  const sensitive = hint.sensitive === true || node.format === 'password' || protectedValue;
  const enumValues = schema.enum || (variants?.every(v => v.const !== undefined) ? variants.map(v => v.const!) : undefined) || (schema.const !== undefined ? [schema.const] : []);
  const object = !protectedValue && (node.type === 'object' || Object.keys(node.properties || {}).length > 0 || (value !== null && typeof value === 'object' && !Array.isArray(value)));
  const array = !protectedValue && (node.type === 'array' || Array.isArray(value));
  const childSet = (key: string, next: JsonValue | undefined) => { const draft = { ...obj(value) }; if (next === undefined) delete draft[key]; else draft[key] = next; set(draft); };
  const matches = !query || `${fieldPath} ${label} ${help || ''} ${JSON.stringify(node.properties || {})}`.toLocaleLowerCase().includes(query.toLocaleLowerCase());
  if (!matches) return null;
  if (depth > 32) return <JsonField label={fieldPath} value={value} set={set} />;
  return <div data-setting-path={fieldPath} className={depth ? 'border-t border-border/65 py-4 first:border-t-0' : ''}>
    <div className="flex items-start justify-between gap-4">
      <button type="button" className="min-w-0 flex-1 text-left" disabled={!object && !array} onClick={() => setOpen(v => !v)} aria-expanded={object || array ? open || !!query : undefined}>
        <span className="flex items-center gap-2 text-sm font-medium">{(object || array) && <ChevronDown size={14} className={open || query ? '' : '-rotate-90'} />}{sensitive && <LockKeyhole size={13} />}{label}</span>
        <span className="mt-1 block break-all font-mono text-[10px] text-muted-foreground">{fieldPath}</span>
        {help && <span className="mt-1 block text-xs leading-5 text-muted-foreground">{help}</span>}
      </button>
      <div className="flex shrink-0 items-center gap-1">
        <button title="JSON" type="button" onClick={() => setRaw(v => !v)} className="rounded-md p-1.5 text-muted-foreground hover:bg-foreground/5"><Code2 size={14} /></button>
        {value !== undefined && <button type="button" aria-label={`${ru ? 'Сбросить' : 'Unset'} ${fieldPath}`} title={ru ? 'Убрать из конфигурации' : 'Remove from configuration'} onClick={() => set(undefined)} className="rounded-md p-1.5 text-muted-foreground hover:bg-foreground/5"><RotateCcw size={13} /></button>}
      </div>
    </div>
    <fieldset disabled={node.readOnly === true} className="mt-3 min-w-0 space-y-3">
    {!!variants?.length && !enumValues.length && <Select aria-label={`${fieldPath} ${ru ? 'тип значения' : 'value type'}`} className="max-w-full text-xs" value={variant ?? ''} onChange={e => { const i = Number(e.target.value); setVariant(i); set(seed(variants[i])); setOpen(true); }}><option value="" disabled>{ru ? 'Тип значения (определён по данным)' : 'Value type (detected)'}</option>{variants.map((v, i) => <option key={i} value={i}>{v.title || (v.const !== undefined ? String(v.const) : v.type || Object.keys(v.properties || {}).join(', ') || `JSON ${i + 1}`)}</option>)}</Select>}
    {raw ? <JsonField label={`${fieldPath} JSON`} value={value} set={set} sensitive={sensitive} /> : object ? (open || query) && <div className={depth ? 'border-l border-border/60 pl-4' : ''}>
      {[...new Set([...Object.keys(node.properties || {}), ...Object.keys(obj(value))])].map(key => <SchemaField key={key} schema={node.properties?.[key] || (typeof node.additionalProperties === 'object' ? node.additionalProperties : {})} value={obj(value)[key]} set={next => childSet(key, next)} path={[...path, key]} hints={hints} depth={depth + 1} query={query} />)}
      {node.additionalProperties !== false && <div className="mt-4 flex gap-2"><Input aria-label={`${fieldPath} ${ru ? 'новый ключ' : 'new key'}`} value={newKey} onChange={e => setNewKey(e.target.value)} placeholder={ru ? 'Имя параметра / профиля' : 'Parameter / profile name'} /><Button size="sm" variant="outline" type="button" disabled={!newKey.trim() || Object.hasOwn(obj(value), newKey.trim()) || ['__proto__', 'constructor', 'prototype'].includes(newKey.trim())} onClick={() => { childSet(newKey.trim(), seed(typeof node.additionalProperties === 'object' ? node.additionalProperties : {})); setNewKey(''); }}><Plus size={14} /></Button></div>}
    </div> : array ? (open || query) && <div className="space-y-2 border-l border-border/60 pl-4">{(Array.isArray(value) ? value : []).map((item, index) => <SchemaField key={index} schema={node.items || {}} value={item} set={next => { const copy = [...(value as JsonValue[])]; if (next === undefined) copy.splice(index, 1); else copy[index] = next; set(copy); }} path={[...path, String(index)]} hints={hints} depth={depth + 1} query={query} />)}<Button size="sm" variant="outline" type="button" onClick={() => set([...(Array.isArray(value) ? value : []), seed(resolveSchema(node.items || {}, undefined))])}><Plus size={14} className="mr-2" />{ru ? 'Добавить элемент' : 'Add item'}</Button></div> : enumValues.length ? <Select aria-label={fieldPath} className="w-full" value={value === undefined ? '' : JSON.stringify(value)} onChange={e => set(e.target.value === '' ? undefined : JSON.parse(e.target.value))}><option value="">{ru ? 'По умолчанию (не задано)' : 'Default (not set)'}</option>{enumValues.map(v => <option key={JSON.stringify(v)} value={JSON.stringify(v)}>{String(v)}</option>)}</Select> : node.type === 'boolean' || typeof value === 'boolean' ? <Select aria-label={fieldPath} value={value === undefined ? '' : String(value)} onChange={e => set(e.target.value === '' ? undefined : e.target.value === 'true')}><option value="">{ru ? 'По умолчанию' : 'Default'}</option><option value="true">{ru ? 'Включено' : 'Enabled'}</option><option value="false">{ru ? 'Выключено' : 'Disabled'}</option></Select> : ['number', 'integer'].includes(String(node.type)) || typeof value === 'number' ? <Input aria-label={fieldPath} type="number" step={node.type === 'integer' ? 1 : 'any'} value={typeof value === 'number' ? value : ''} placeholder={ru ? 'По умолчанию' : 'Default'} onChange={e => set(e.target.value === '' ? undefined : Number(e.target.value))} /> : typeof value === 'object' && value !== null ? <JsonField label={fieldPath} value={value} set={set} /> : <Input aria-label={fieldPath} type={sensitive ? 'password' : 'text'} autoComplete="off" spellCheck={false} value={protectedValue ? '' : value === undefined || value === null ? '' : String(value)} placeholder={protectedValue ? ru ? 'Сохранено · пустое поле не меняет секрет' : 'Saved · leave blank to keep secret' : ru ? 'Не задано' : 'Not set'} onChange={e => set(protectedValue && e.target.value === '' ? value : e.target.value)} />}
    </fieldset>
  </div>;
}

export function SettingsBrowser({ category, connected, scope, title = true, onDirty }: { category: string; connected: boolean; scope: string; title?: boolean; onDirty?(dirty: boolean): void }) {
  const ru = usePreferences().language === 'ru'; const [catalog, setCatalog] = useState<SettingsCatalog | null>(null); const [root, setRoot] = useState(''); const [document, setDocument] = useState<SettingsDocument | null>(null); const [draft, setDraft] = useState<JsonValue>({}); const [query, setQuery] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [reload, setReload] = useState(0); const [confirm, setConfirm] = useState(false); const [pendingRoot, setPendingRoot] = useState<string | null>(null);
  const dirty = !!document && JSON.stringify(document.value) !== JSON.stringify(draft);
  useEffect(() => { onDirty?.(dirty); return () => onDirty?.(false); }, [dirty, onDirty]);
  const roots = useMemo(() => catalog?.roots.filter(r => category === 'advanced' || gatewayCategories[category]?.includes(r.key)) || [], [catalog, category]);
  useEffect(() => { let alive = true; setCatalog(null); setDocument(null); setRoot(''); setError(''); if (connected) void window.pincer.settings.catalog().then(result => { if (alive) { if (result.ok) setCatalog(result.value); else setError(result.error.message); } }); return () => { alive = false; }; }, [connected, scope, category]);
  useEffect(() => { if (roots.length && !roots.some(r => r.key === root)) setRoot(roots[0].key); }, [roots, root]);
  useEffect(() => { let alive = true; setDocument(null); setError(''); if (!root || !connected) return; setBusy(true); void window.pincer.settings.section(root).then(result => { if (alive) { if (result.ok) { setDocument(result.value); setDraft(result.value.value); } else setError(result.error.message); } }).finally(() => { if (alive) setBusy(false); }); return () => { alive = false; }; }, [root, reload, scope, connected]);
  return <section className="space-y-5" data-testid="gateway-settings-browser">
    {title && <div><h3 className="text-lg font-semibold">{ru ? 'Все параметры Gateway' : 'All Gateway settings'}</h3><p className="mt-2 text-xs leading-5 text-muted-foreground">{ru ? 'Полная схема установленного OpenClaw, включая вложенные поля. Изменения применяются на сервере; локальные настройки Pincer находятся выше. Параметры и описания ниже предоставлены Gateway.' : 'Complete schema of the installed OpenClaw, including nested fields. Changes apply on the server; local Pincer preferences are above. Field names and descriptions below come from Gateway.'}</p></div>}
    {!connected && <p className="text-sm text-muted-foreground">{ru ? 'Подключитесь к Gateway, чтобы загрузить его настройки.' : 'Connect to Gateway to load its settings.'}</p>}
    {catalog && <div className="space-y-3"><label className="block text-xs text-muted-foreground">{ru ? 'Раздел конфигурации' : 'Configuration section'}<Select data-testid="gateway-settings-root" className="mt-2 w-full" value={root} onChange={e => { if (dirty) setPendingRoot(e.target.value); else setRoot(e.target.value); }}>{roots.map(r => <option key={r.key} value={r.key}>{rootLabels[r.key]?.[ru ? 0 : 1] || r.title} · {r.key}</option>)}</Select></label><div className="relative"><Search size={14} className="absolute left-3 top-3 text-muted-foreground" /><Input className="pl-9" value={query} onChange={e => setQuery(e.target.value)} placeholder={ru ? 'Найти вложенный параметр…' : 'Find nested setting…'} aria-label={ru ? 'Поиск параметров Gateway' : 'Search Gateway settings'} /></div><p className="text-[11px] text-muted-foreground">OpenClaw {catalog.version} · {catalog.roots.length} {ru ? 'разделов в полной схеме' : 'sections in the complete schema'}</p>{!roots.length && <p className="text-sm text-muted-foreground">{ru ? 'У этой версии Gateway нет параметров для раздела. Полная схема доступна в «Расширенные».' : 'This Gateway version has no settings for this category. The complete schema is under Advanced.'}</p>}</div>}
    {error && <p role="alert" className="rounded-xl border border-destructive/40 p-3 text-sm text-destructive">{errorText(error, ru)}</p>}
    {busy && <p role="status" className="text-sm text-muted-foreground">{ru ? 'Загрузка…' : 'Loading…'}</p>}
    {document && <><div className="rounded-2xl border border-border bg-surface-modal px-5 py-4"><SchemaField key={document.lease} schema={document.schema} value={draft} set={value => setDraft(value ?? {})} path={[root]} hints={document.hints} query={query} /></div><div className="sticky bottom-0 flex flex-wrap items-center gap-3 rounded-xl border border-border bg-surface-chat p-3 shadow-sm"><Button disabled={!dirty || busy || !connected} onClick={() => setConfirm(true)}><SlidersHorizontal size={14} className="mr-2" />{ru ? 'Сохранить на Gateway' : 'Save to Gateway'}</Button><Button variant="ghost" disabled={busy} onClick={() => { if (dirty) setPendingRoot(root); else setReload(v => v + 1); }}>{ru ? 'Обновить' : 'Reload'}</Button><span className="text-xs text-muted-foreground">{dirty ? ru ? 'Есть несохранённые изменения' : 'Unsaved changes' : ru ? 'Изменения не вносились' : 'No changes'}</span></div></>}
    {confirm && document && <Modal open title={ru ? 'Применить настройки Gateway?' : 'Apply Gateway settings?'} close={() => { if (!busy) setConfirm(false); }}><p className="text-sm leading-6 text-muted-foreground">{ru ? `Изменится раздел «${rootLabels[root]?.[0] || root}» на сервере. Удалённые поля будут сброшены. Gateway может перезапуститься, а активные задачи — прерваться. Другие разделы не меняются.` : `The “${rootLabels[root]?.[1] || root}” server section will change. Removed fields will be reset. Gateway may restart and interrupt active tasks. Other sections remain unchanged.`}</p><div className="mt-5 flex justify-end gap-2"><Button variant="ghost" disabled={busy} onClick={() => setConfirm(false)}>{ru ? 'Отмена' : 'Cancel'}</Button><Button disabled={busy} onClick={() => { setBusy(true); setError(''); void window.pincer.settings.save(document.lease, draft).then(result => { if (result.ok) { setConfirm(false); toast.success(ru ? 'Настройки сохранены на Gateway' : 'Settings saved on Gateway'); setReload(v => v + 1); } else { setError(result.error.message); setConfirm(false); } }).finally(() => setBusy(false)); }}>{ru ? 'Применить изменения' : 'Apply changes'}</Button></div></Modal>}
    {pendingRoot !== null && <Modal open title={ru ? 'Отбросить изменения?' : 'Discard changes?'} close={() => setPendingRoot(null)}><p className="text-sm text-muted-foreground">{ru ? 'Правки этого раздела ещё не сохранены на Gateway.' : 'Changes to this section have not been saved on Gateway.'}</p><div className="mt-5 flex justify-end gap-2"><Button variant="ghost" onClick={() => setPendingRoot(null)}>{ru ? 'Продолжить редактирование' : 'Keep editing'}</Button><Button onClick={() => { setRoot(pendingRoot); setReload(v => v + 1); setPendingRoot(null); }}>{ru ? 'Отбросить' : 'Discard'}</Button></div></Modal>}
  </section>;
}
